name: Arduino Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Arduino Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run arduino-lint
        uses: arduino/arduino-lint-action@v1
        with:
          project-type: library
